[package]
name = "krapslog"
version = "0.1.0"
authors = ["Adam Jensen <acjensen@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
atty = "0.2"
chrono = "0.4"
lazy_static = "1.4"
regex = "1.3"
sparkline = "0.1"
terminal_size = "0.1"