[package]
name = "krapslog"
version = "0.3.2"
authors = ["Adam Jensen <adam@acj.sh>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/acj/krapslog-rs"
description = "Visualize log files using sparklines"
readme = "README.md"
keywords = ["sparklines", "logs", "dataviz", "debugging"]
categories = ["command-line-utilities", "parser-implementations", "visualization"]
exclude = [
    ".github/*",
]

[lib]
name = "krapslog"
path = "src/lib.rs"

[[bin]]
name = "krapslog"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0"
atty = "0.2"
chrono = "0.4"
clap = "2.33"
indicatif = "0.16.2"
lazy_static = "1.4"
progress-streams = "1.1"
regex = "1.4.2"
terminal_size = "0.1"