[package]
name = "krapslog-rs"
version = "0.1.0"
authors = ["Adam Jensen <acjensen@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.12"
lazy_static = "1.4.0"
regex = "1.3.9"
sparkline = "0.1.1"
terminal_size = "0.1.13"