name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - name: Build
      run: cargo build --release --locked
    - name: Run tests
      run: cargo test --release --locked
    - name: Run format check and linter
      run: cargo fmt -- --check && cargo clippy -- -Dwarnings
