name: Release to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
