name: Release to crates.io

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@984d158d699777abbaa79de23de3134e60c187fa # stable branch
      - run: |
          cargo login ${{ secrets.CARGO_TOKEN }}
          cargo publish
